hapi:
  fhir:
    version: r4
    server:
      path: /fhir/*
    rest:
      server-name: hapi-fhir-spring-boot-sample-server-jersey
      server-version: 1.0.0
      implementation-description: Spring Boot Jersey Server Sample
      default-response-encoding: json
      e-tag-support: enabled
      default-pretty-print: true
    validation:
      enabled: false
      request-only: false
logging:
  level:
    ca.uhn.fhir.jaxrs: debug